export const category = [
  null,
  { c_id: 1, main: "life", sub: "business" },
  { c_id: 2, main: "life", sub: "culture" },
  { c_id: 3, main: "life", sub: "entertainment" },
  { c_id: 4, main: "life", sub: "etc" },
  { c_id: 5, main: "life", sub: "family" },
  { c_id: 6, main: "life", sub: "fitness" },
  { c_id: 7, main: "life", sub: "food" },
  { c_id: 8, main: "life", sub: "health" },
  { c_id: 9, main: "life", sub: "home" },
  { c_id: 10, main: "life", sub: "movies" },
  { c_id: 11, main: "life", sub: "music" },
  { c_id: 12, main: "life", sub: "people" },
  { c_id: 13, main: "life", sub: "pets" },
  { c_id: 14, main: "life", sub: "real estate" },
  { c_id: 15, main: "life", sub: "shopping" },
  { c_id: 16, main: "life", sub: "style" },
  { c_id: 17, main: "life", sub: "travel" },
  { c_id: 18, main: "life", sub: "tv" },
  { c_id: 19, main: "life", sub: "wedding" },
  { c_id: 20, main: "news", sub: "columns" },
  { c_id: 21, main: "news", sub: "etc" },
  { c_id: 22, main: "news", sub: "factcheck" },
  { c_id: 23, main: "news", sub: "nation" },
  { c_id: 24, main: "news", sub: "opinion" },
  { c_id: 25, main: "news", sub: "politics" },
  { c_id: 26, main: "news", sub: "shows" },
  { c_id: 27, main: "news", sub: "social" },
  { c_id: 28, main: "other", sub: "auto" },
  { c_id: 29, main: "other", sub: "business" },
  { c_id: 30, main: "other", sub: "climate" },
  { c_id: 31, main: "other", sub: "college" },
  { c_id: 32, main: "other", sub: "companies" },
  { c_id: 33, main: "other", sub: "covid-19" },
  { c_id: 34, main: "other", sub: "economy" },
  { c_id: 35, main: "other", sub: "education" },
  { c_id: 36, main: "other", sub: "environment" },
  { c_id: 37, main: "other", sub: "etc" },
  { c_id: 38, main: "other", sub: "law" },
  { c_id: 39, main: "other", sub: "science" },
  { c_id: 40, main: "sport", sub: "gaelic-games" },
  { c_id: 41, main: "sports", sub: "" },
  { c_id: 42, main: "sports", sub: "athletics" },
  { c_id: 43, main: "sports", sub: "baseball" },
  { c_id: 44, main: "sports", sub: "basketball" },
  { c_id: 45, main: "sports", sub: "boxing" },
  { c_id: 46, main: "sports", sub: "cricket" },
  { c_id: 47, main: "sports", sub: "cycling" },
  { c_id: 48, main: "sports", sub: "etc" },
  { c_id: 49, main: "sports", sub: "fighting" },
  { c_id: 50, main: "sports", sub: "football" },
  { c_id: 51, main: "sports", sub: "golf" },
  { c_id: 52, main: "sports", sub: "gymnastics" },
  { c_id: 53, main: "sports", sub: "hockey" },
  { c_id: 54, main: "sports", sub: "horseracing" },
  { c_id: 55, main: "sports", sub: "motorsport" },
  { c_id: 56, main: "sports", sub: "olympics" },
  { c_id: 57, main: "sports", sub: "rugby" },
  { c_id: 58, main: "sports", sub: "snooker" },
  { c_id: 59, main: "sports", sub: "soccer" },
  { c_id: 60, main: "sports", sub: "swimming" },
  { c_id: 61, main: "sports", sub: "tennis" },
  { c_id: 62, main: "tech", sub: "companies" },
  { c_id: 63, main: "tech", sub: "etc" },
  { c_id: 64, main: "tech", sub: "fbi" },
  { c_id: 65, main: "tech", sub: "review" },
  { c_id: 66, main: "tech", sub: "sns" },
  {
    c_id: 67,
    main: "world",
    sub: "africa",
    coordinates: [0, 25],
    kor: "아프리카",
    img: require("assets/africa.png"),
  },
  {
    c_id: 68,
    main: "world",
    sub: "americas",
    coordinates: [45, 255],
    kor: "북 아메리카",
    img: require("assets/north-america.png"),
  },
  {
    c_id: 69,
    main: "world",
    sub: "asia",
    coordinates: [48, 88],
    kor: "아시아",
    img: require("assets/asia.png"),
  },
  {
    c_id: 70,
    main: "world",
    sub: "australia",
    coordinates: [335, 132],
    kor: "오스트레일리아",
    img: require("assets/australia.png"),
  },
  {
    c_id: 71,
    main: "world",
    sub: "brazil",
    coordinates: [346, 310],
    kor: "브라질",
    img: require("assets/brazil.png"),
  },
  {
    c_id: 72,
    main: "world",
    sub: "canada",
    coordinates: [52, 264],
    kor: "캐나다",
    img: require("assets/canada.png"),
  },
  {
    c_id: 73,
    main: "world",
    sub: "china",
    coordinates: [35, 103.5],
    kor: "중국",
    img: require("assets/china.png"),
  },
  {
    c_id: 74,
    main: "world",
    sub: "etc",
    coordinates: [180, 0],
    kor: "기타",
    img: require("assets/etc.png"),
  },
  {
    c_id: 75,
    main: "world",
    sub: "europe",
    coordinates: [48, 10],
    kor: "유럽",
    img: require("assets/europe.png"),
  },
  {
    c_id: 76,
    main: "world",
    sub: "france",
    coordinates: [46, 4],
    kor: "프랑스",
    img: require("assets/france.png"),
  },
  {
    c_id: 77,
    main: "world",
    sub: "germany",
    coordinates: [51, 10],
    kor: "독일",
    img: require("assets/germany.png"),
  },
  {
    c_id: 78,
    main: "world",
    sub: "hongkong",
    coordinates: [22.317, 113.917],
    kor: "홍콩",
    img: require("assets/hongkong.png"),
  },
  {
    c_id: 79,
    main: "world",
    sub: "india",
    coordinates: [22, 81],
    kor: "인도",
    img: require("assets/india.png"),
  },
  {
    c_id: 80,
    main: "world",
    sub: "iran",
    coordinates: [32, 50],
    kor: "이란",
    img: require("assets/iran.png"),
  },
  {
    c_id: 81,
    main: "world",
    sub: "iraq",
    coordinates: [33, 43],
    kor: "이라크",
    img: require("assets/iraq.png"),
  },
  {
    c_id: 82,
    main: "world",
    sub: "israel",
    coordinates: [31.776, 35.228],
    kor: "이스라엘",
    img: require("assets/israel.png"),
  },
  {
    c_id: 83,
    main: "world",
    sub: "italy",
    coordinates: [41.892, 12.511],
    kor: "이탈리아",
    img: require("assets/italy.png"),
  },
  {
    c_id: 84,
    main: "world",
    sub: "japan",
    coordinates: [35.6894, 139.692],
    kor: "일본",
    img: require("assets/japan.png"),
  },
  {
    c_id: 85,
    main: "world",
    sub: "lebanon",
    coordinates: [33.5, 35.5],
    kor: "레바논",
    img: require("assets/lebanon.png"),
  },
  {
    c_id: 86,
    main: "world",
    sub: "mexico",
    coordinates: [23, 258],
    kor: "멕시코",
    img: require("assets/mexico.png"),
  },
  {
    c_id: 87,
    main: "world",
    sub: "middle east",
    coordinates: [24, 54],
    kor: "중동",
    img: require("assets/middle-east.png"),
  },
  {
    c_id: 88,
    main: "world",
    sub: "north korea",
    coordinates: [38, 128],
    kor: "북한",
    img: require("assets/north-korea.png"),
  },
  {
    c_id: 89,
    main: "world",
    sub: "northern ireland",
    coordinates: [56, 358],
    kor: "북아일랜드",
    img: require("assets/northern-ireland.png"),
  },
  {
    c_id: 90,
    main: "world",
    sub: "russia",
    coordinates: [63, 105],
    kor: "러시아",
    img: require("assets/russia.png"),
  },
  {
    c_id: 91,
    main: "world",
    sub: "saudiarabia",
    coordinates: [24, 44.5],
    kor: "사우디아라비아",
    img: require("assets/saudiarabia.png"),
  },
  {
    c_id: 92,
    main: "world",
    sub: "south korea",
    coordinates: [37.541, 126.986],
    kor: "대한민국",
    img: require("assets/kor.jpg"),
  },
  {
    c_id: 93,
    main: "world",
    sub: "spain",
    coordinates: [39, 0],
    kor: "스페인",
    img: require("assets/spain.png"),
  },
  {
    c_id: 94,
    main: "world",
    sub: "turkey",
    coordinates: [39, 32],
    kor: "튀르키예",
    img: require("assets/turkey.png"),
  },
  {
    c_id: 95,
    main: "world",
    sub: "uk",
    coordinates: [54, 358],
    kor: "영국",
    img: require("assets/uk.png"),
  },
  {
    c_id: 96,
    main: "world",
    sub: "ukraine",
    coordinates: [48, 31],
    kor: "우크라이나",
    img: require("assets/ukraine.png"),
  },
  {
    c_id: 97,
    main: "world",
    sub: "us",
    coordinates: [36.5, 265],
    kor: "미국",
    img: require("assets/usa.jpg"),
  },
];
